### ISSUE TITLE
`There should be no space after '{'` Error when passing object into jsx

### ISSUE THREAD

**Issue by bryceosterhaus** [natecavanaugh/check-source-formatting#19]
For linting jsx, this error has been happening for us. Is this expected?

```jsx
<MyComponent
     configObj={                //Error occurs here
          {
                 foo: 'bar'
          }
      }
/>
```

**Comment by natecavanaugh** [comment]
Heya Bryce,
Yeah, I saw this one recently and I wasn't 100% sure what to do about it either.

I could only think of 3 possible solutions:

1. Assigning the `configObj` to a variable outside of the JSX context, and only pass that
2. Change the formatting from:

    ```js
    configObj={
        {
            ...
        }
    }
    ```
to

    ```js
    configObj={{
        ...
    }}
    ```
3. Copy the rule implementation, and tweak it to allow indenting of objects.

Do you guys have any thoughts on this one?

**Comment by mthadley** [comment]
If it was my choice, I'd probably go for number 2 (I usually prefer the terser styles anyways).

**Comment by bryceosterhaus** [comment]
Yeah I would also prefer #2, would hope for same formatting for arrays as well.

```js
configObj={[
    ...
]}
```

**Comment by natecavanaugh** [comment]
Hey guys,
I'm good with going with that change :) I'll also look into some other ways of enforcing that particular formatting style.

Thanks for the input guys.
