### ISSUE TITLE
Double output?

### ISSUE THREAD

**Issue by drewbrokke** [natecavanaugh/check-source-formatting#5]
When notifying of mixed tabs and spaces, two lines will be printed:
```
    Line 62: Mixed spaces and tabs.
    Line 62: Mixed spaces and tabs: if (Surface.isActionURL(event.path)) {
```
Is this intentional?

**Comment by natecavanaugh** [comment]
Heya Drew,
This definitely isn't intentional. Thanks for reminding me of it :)
